# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -mtriple=riscv64 -run-pass=riscv-expand-vxpseudo -o - | FileCheck %s

--- |
  define dso_local void @add_coeff4(ptr nocapture noundef %dst, ptr noalias nocapture noundef readonly %src1, i32 noundef signext %N, ptr noalias nocapture noundef readonly %src2, ptr noalias nocapture noundef readonly %src3, ptr noalias nocapture noundef readonly %src4, float noundef nofpclass(nan inf) %k1, float noundef nofpclass(nan inf) %k2, float noundef nofpclass(nan inf) %k3, float noundef nofpclass(nan inf) %k4) local_unnamed_addr #0 {
  entry:
    %cmp25 = icmp sgt i32 %N, 0
    br i1 %cmp25, label %for.body.preheader, label %for.cond.cleanup

  for.body.preheader:                               ; preds = %entry
    %wide.trip.count = zext nneg i32 %N to i64
    br label %vector.body

  vector.body:                                      ; preds = %vector.body, %for.body.preheader
    %evl.based.iv = phi i64 [ 0, %for.body.preheader ], [ %index.evl.next, %vector.body ]
    %0 = sub i64 %wide.trip.count, %evl.based.iv
    %1 = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %0, i32 16, i1 true)
    %2 = getelementptr inbounds float, ptr %src1, i64 %evl.based.iv
    %vp.op.load = tail call <vscale x 16 x float> @llvm.vp.load.nxv16f32.p0(ptr align 4 %2, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1), !tbaa !9
    %3 = insertelement <vscale x 16 x float> poison, float %k1, i64 0
    %4 = shufflevector <vscale x 16 x float> %3, <vscale x 16 x float> poison, <vscale x 16 x i32> zeroinitializer
    %vp.op = tail call fast <vscale x 16 x float> @llvm.vp.fmul.nxv16f32(<vscale x 16 x float> %vp.op.load, <vscale x 16 x float> %4, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %5 = getelementptr inbounds float, ptr %src2, i64 %evl.based.iv
    %vp.op.load28 = tail call <vscale x 16 x float> @llvm.vp.load.nxv16f32.p0(ptr align 4 %5, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1), !tbaa !9
    %6 = insertelement <vscale x 16 x float> poison, float %k2, i64 0
    %7 = shufflevector <vscale x 16 x float> %6, <vscale x 16 x float> poison, <vscale x 16 x i32> zeroinitializer
    %vp.op31 = tail call fast <vscale x 16 x float> @llvm.vp.fmul.nxv16f32(<vscale x 16 x float> %vp.op.load28, <vscale x 16 x float> %7, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %vp.op32 = tail call fast <vscale x 16 x float> @llvm.vp.fadd.nxv16f32(<vscale x 16 x float> %vp.op31, <vscale x 16 x float> %vp.op, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %8 = getelementptr inbounds float, ptr %dst, i64 %evl.based.iv
    %vp.op.load33 = tail call <vscale x 16 x float> @llvm.vp.load.nxv16f32.p0(ptr align 4 %8, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1), !tbaa !9
    %vp.op34 = tail call fast <vscale x 16 x float> @llvm.vp.fadd.nxv16f32(<vscale x 16 x float> %vp.op32, <vscale x 16 x float> %vp.op.load33, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %9 = getelementptr inbounds float, ptr %src3, i64 %evl.based.iv
    %vp.op.load35 = tail call <vscale x 16 x float> @llvm.vp.load.nxv16f32.p0(ptr align 4 %9, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1), !tbaa !9
    %10 = insertelement <vscale x 16 x float> poison, float %k3, i64 0
    %11 = shufflevector <vscale x 16 x float> %10, <vscale x 16 x float> poison, <vscale x 16 x i32> zeroinitializer
    %vp.op38 = tail call fast <vscale x 16 x float> @llvm.vp.fmul.nxv16f32(<vscale x 16 x float> %vp.op.load35, <vscale x 16 x float> %11, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %12 = getelementptr inbounds float, ptr %src4, i64 %evl.based.iv
    %vp.op.load39 = tail call <vscale x 16 x float> @llvm.vp.load.nxv16f32.p0(ptr align 4 %12, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1), !tbaa !9
    %13 = insertelement <vscale x 16 x float> poison, float %k4, i64 0
    %14 = shufflevector <vscale x 16 x float> %13, <vscale x 16 x float> poison, <vscale x 16 x i32> zeroinitializer
    %vp.op42 = tail call fast <vscale x 16 x float> @llvm.vp.fmul.nxv16f32(<vscale x 16 x float> %vp.op.load39, <vscale x 16 x float> %14, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %vp.op43 = tail call fast <vscale x 16 x float> @llvm.vp.fadd.nxv16f32(<vscale x 16 x float> %vp.op38, <vscale x 16 x float> %vp.op34, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    %vp.op44 = tail call fast <vscale x 16 x float> @llvm.vp.fadd.nxv16f32(<vscale x 16 x float> %vp.op43, <vscale x 16 x float> %vp.op42, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1)
    tail call void @llvm.vp.store.nxv16f32.p0(<vscale x 16 x float> %vp.op44, ptr align 4 %8, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %1), !tbaa !9
    %15 = zext i32 %1 to i64
    %index.evl.next = add i64 %evl.based.iv, %15
    %16 = zext i32 %1 to i64
    %index.next = add i64 %evl.based.iv, %16
    %17 = icmp eq i64 %index.next, %wide.trip.count
    br i1 %17, label %for.cond.cleanup, label %vector.body, !llvm.loop !13

  for.cond.cleanup:                                 ; preds = %vector.body, %entry
    ret void
  }

  !9 = !{!10, !10, i64 0}
  !10 = !{!"float", !11, i64 0}
  !11 = !{!"omnipotent char", !12, i64 0}
  !12 = !{!"Simple C/C++ TBAA"}
  !13 = distinct !{!13, !14, !15, !16}
  !14 = !{!"llvm.loop.mustprogress"}
  !15 = !{!"llvm.loop.isvectorized", i32 1}
  !16 = !{!"llvm.loop.unroll.runtime.disable"}

...
---
name:            add_coeff4
body:             |
  ; CHECK-LABEL: name: add_coeff4
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.3(0x30000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $f10_f, $f11_f, $f12_f, $f13_f
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:fpr32 = COPY killed $f13_f
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:fpr32 = COPY killed $f12_f
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:fpr32 = COPY killed $f11_f
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:fpr32 = COPY killed $f10_f
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY killed $x15
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY killed $x14
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr = COPY killed $x13
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr = COPY killed $x12
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gpr = COPY killed $x11
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:gpr = COPY killed $x10
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BGE killed [[COPY10]], [[COPY7]], %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body.preheader:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:gpr = COPY killed [[COPY7]]
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:gpr = COPY killed [[COPY12]]
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:gpr = COPY [[COPY11]]
  ; CHECK-NEXT:   [[PseudoVFMV_V_FPR32_M8_:%[0-9]+]]:vrm8 = PseudoVFMV_V_FPR32_M8 $noreg, [[COPY3]], -1, 5 /* e32 */, 3 /* ta, ma */
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:gpr = COPY killed [[COPY13]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.vector.body:
  ; CHECK-NEXT:   successors: %bb.3(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:gpr = COPY killed [[COPY15]]
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:gprnox0 = SUB [[COPY11]], [[COPY16]]
  ; CHECK-NEXT:   [[PseudoVSETVLI:%[0-9]+]]:gprnox0 = PseudoVSETVLI killed [[SUB]], 193 /* e8, m2, ta, ma */, implicit-def dead $vl, implicit-def dead $vtype
  ; CHECK-NEXT:   [[SH2ADD:%[0-9]+]]:gpr = SH2ADD [[COPY16]], [[COPY8]]
  ; CHECK-NEXT:   [[PseudoVLE32_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 undef [[PseudoVLE32_V_M8_]], killed [[SH2ADD]], [[PseudoVSETVLI]], 5 /* e32 */, 2 /* tu, ma */
  ; CHECK-NEXT:   [[SH2ADD1:%[0-9]+]]:gpr = SH2ADD [[COPY16]], [[COPY6]]
  ; CHECK-NEXT:   [[PseudoVLE32_V_M8_1:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 undef [[PseudoVLE32_V_M8_1]], killed [[SH2ADD1]], [[PseudoVSETVLI]], 5 /* e32 */, 2 /* tu, ma */
  ; CHECK-NEXT:   [[SH2ADD2:%[0-9]+]]:gpr = SH2ADD [[COPY16]], [[COPY9]]
  ; CHECK-NEXT:   [[PseudoVLE32_V_M8_2:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 undef [[PseudoVLE32_V_M8_2]], [[SH2ADD2]], [[PseudoVSETVLI]], 5 /* e32 */, 2 /* tu, ma */
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:vrm8 = COPY killed [[PseudoVLE32_V_M8_2]]
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMACC_VV_M8_E32 [[COPY17]], [[PseudoVFMV_V_FPR32_M8_]], killed [[PseudoVLE32_V_M8_]], 7, [[PseudoVSETVLI]], 5 /* e32 */, 3 /* ta, ma */, implicit $frm
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:vrm8 = COPY killed [[COPY17]]
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMACC_VFPR32_M8_E32 [[COPY18]], [[COPY2]], killed [[PseudoVLE32_V_M8_1]], 7, [[PseudoVSETVLI]], 5 /* e32 */, 3 /* ta, ma */, implicit $frm
  ; CHECK-NEXT:   [[SH2ADD3:%[0-9]+]]:gpr = SH2ADD [[COPY16]], [[COPY5]]
  ; CHECK-NEXT:   [[PseudoVLE32_V_M8_3:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 undef [[PseudoVLE32_V_M8_3]], killed [[SH2ADD3]], [[PseudoVSETVLI]], 5 /* e32 */, 2 /* tu, ma */
  ; CHECK-NEXT:   [[SH2ADD4:%[0-9]+]]:gpr = SH2ADD [[COPY16]], [[COPY4]]
  ; CHECK-NEXT:   [[PseudoVLE32_V_M8_4:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 undef [[PseudoVLE32_V_M8_4]], killed [[SH2ADD4]], [[PseudoVSETVLI]], 5 /* e32 */, 2 /* tu, ma */
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:vrm8 = COPY killed [[PseudoVLE32_V_M8_3]]
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMADD_VFPR32_M8_E32 [[COPY19]], [[COPY1]], killed [[COPY18]], 7, [[PseudoVSETVLI]], 5 /* e32 */, 3 /* ta, ma */, implicit $frm
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:vrm8 = COPY killed [[COPY19]]
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMACC_VFPR32_M8_E32 [[COPY20]], [[COPY]], killed [[PseudoVLE32_V_M8_4]], 7, [[PseudoVSETVLI]], 5 /* e32 */, 3 /* ta, ma */, implicit $frm
  ; CHECK-NEXT:   PseudoVSE32_V_M8 killed [[COPY20]], killed [[SH2ADD2]], [[PseudoVSETVLI]], 5 /* e32 */
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD killed [[COPY16]], killed [[PseudoVSETVLI]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:gpr = COPY [[ADD]]
  ; CHECK-NEXT:   BNE killed [[ADD]], [[COPY14]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.cond.cleanup:
  ; CHECK-NEXT:   PseudoRET
  bb.0.entry:
    successors: %bb.1(0x50000000), %bb.3(0x30000000)
    liveins: $x10, $x11, $x12, $x13, $x14, $x15, $f10_f, $f11_f, $f12_f, $f13_f

    %12:fpr32 = COPY killed $f13_f
    %11:fpr32 = COPY killed $f12_f
    %10:fpr32 = COPY killed $f11_f
    %9:fpr32 = COPY killed $f10_f
    %8:gpr = COPY killed $x15
    %7:gpr = COPY killed $x14
    %6:gpr = COPY killed $x13
    %5:gpr = COPY killed $x12
    %4:gpr = COPY killed $x11
    %3:gpr = COPY killed $x10
    %14:gpr = COPY $x0
    BGE killed %14, %5, %bb.3
    PseudoBR %bb.1

  bb.1.for.body.preheader:
    %13:gpr = COPY killed %5
    %16:gpr = COPY $x0
    %15:gpr = COPY killed %16
    %0:gpr = COPY %13
    %38:gpr = COPY killed %15

  bb.2.vector.body:
    successors: %bb.3(0x04000000), %bb.2(0x7c000000)

    %1:gpr = COPY killed %38
    %17:gprnox0 = SUB %13, %1
    %18:gprnox0 = PseudoVSETVLI killed %17, 193 /* e8, m2, ta, ma */, implicit-def dead $vl, implicit-def dead $vtype
    %19:gpr = SH2ADD %1, %4
    %20:vrm8 = PseudoVLE32_V_M8 undef %20, killed %19, %18, 5 /* e32 */, 2 /* tu, ma */
    %21:gpr = SH2ADD %1, %6
    %22:vrm8 = PseudoVLE32_V_M8 undef %22, killed %21, %18, 5 /* e32 */, 2 /* tu, ma */
    %23:gpr = SH2ADD %1, %3
    %24:vrm8 = PseudoVLE32_V_M8 undef %24, %23, %18, 5 /* e32 */, 2 /* tu, ma */
    %25:vrm8 = COPY killed %24
    %25:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMACC_VFPR32_M8_E32 %25, %9, killed %20, 7, %18, 5 /* e32 */, 3 /* ta, ma */, implicit $frm
    %26:vrm8 = COPY killed %25
    %26:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMACC_VFPR32_M8_E32 %26, %10, killed %22, 7, %18, 5 /* e32 */, 3 /* ta, ma */, implicit $frm
    %27:gpr = SH2ADD %1, %7
    %28:vrm8 = PseudoVLE32_V_M8 undef %28, killed %27, %18, 5 /* e32 */, 2 /* tu, ma */
    %29:gpr = SH2ADD %1, %8
    %30:vrm8 = PseudoVLE32_V_M8 undef %30, killed %29, %18, 5 /* e32 */, 2 /* tu, ma */
    %31:vrm8 = COPY killed %28
    %31:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMADD_VFPR32_M8_E32 %31, %11, killed %26, 7, %18, 5 /* e32 */, 3 /* ta, ma */, implicit $frm
    %32:vrm8 = COPY killed %31
    %32:vrm8 = nnan ninf nsz arcp contract afn reassoc nofpexcept PseudoVFMACC_VFPR32_M8_E32 %32, %12, killed %30, 7, %18, 5 /* e32 */, 3 /* ta, ma */, implicit $frm
    PseudoVSE32_V_M8 killed %32, killed %23, %18, 5 /* e32 */
    %2:gpr = ADD killed %1, killed %18
    %38:gpr = COPY %2
    BNE killed %2, %0, %bb.2
    PseudoBR %bb.3

  bb.3.for.cond.cleanup:
    PseudoRET

...
